Document: cuteexplorer
Title: Debian cuteexplorer Manual
Author: <insert document author here>
Abstract: This manual describes what cuteexplorer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cuteexplorer/cuteexplorer.sgml.gz

Format: postscript
Files: /usr/share/doc/cuteexplorer/cuteexplorer.ps.gz

Format: text
Files: /usr/share/doc/cuteexplorer/cuteexplorer.text.gz

Format: HTML
Index: /usr/share/doc/cuteexplorer/html/index.html
Files: /usr/share/doc/cuteexplorer/html/*.html

  
